name: deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Until 2.0 is released
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc

      - name: Install JS dependencies
        run: |
          deno install

      - name: Build website
        run: |
          deno run build
        env:
          ASTRO_TELEMETRY_DISABLED: 1

      - name: Cache website
        id: cache-build
        uses: actions/cache@v4
        with:
          path: dist
          key: >
            website
            ${{ github.run_id }}
            ${{ github.run_attempt }}

  cf-pages:
    uses: ./.github/workflows/deploy-cf-pages.yml
    needs: [build]
    secrets: inherit

  post-deploy:
    uses: ./.github/workflows/deploy-post.yml
    needs: [cf-pages]
    secrets: inherit
