name: pre-commit

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: pre-commit-${{ github.head_ref }}
  cancel-in-progress: true

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: actionlint
